[package]
name = "universal_config_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.10.0"
rfd = { version = "0.13.0", default-features = false, features = ["tokio", "xdg-portal"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
