[package]
name = "universal_config_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
relm4 = { version = "0.6.2", features = ["libadwaita"] }
relm4-components = "0.6.2"
